name: Brandon
favicon: null
layout_spectrum: 0.1677909
typography_spectrum: 0.8946037
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Brandon Bohling
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3466496712062508
  lightness: 0.5168634
  saturation: 0.4055649
  rhythmicContrast: 0.5758854
purpose: []
