name: Brandon
favicon: null
layout_spectrum: 0.9657
typography_spectrum: 0.84757
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Brandon Bohling
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-72006039-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#58585a'
    - '#bdbec0'
    - '#ffdf16'
    - '#000000'
    - '#ffffff'
  brandStrength: 0.25
  lightness: 0.5168634
  saturation: 0.5
  rhythmicContrast: 0.5758854
purpose: []
